server:
  error:
    # show error message when throwing error
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    # save H2 database in /src/main/resources/h2data
    # file name = database.mv.db
    url: jdbc:h2:file:./src/main/resources/h2data/database
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
